name = "vibration-monitoring-system"
main = "functions/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "vibration-monitoring"
compatibility_flags = { nodejs_compat = true }

[env.staging]
name = "vibration-monitoring-staging"
compatibility_flags = { nodejs_compat = true }

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secure-jwt-secret-key-here-change-this"

[[kv_namespaces]]
binding = "DB"
database_name = "vibration-monitoring-db"
database_id = ""

[[kv_namespaces]]
binding = "CACHE"
id = ""

[build]
command = "npm run build"
cwd = "."
watch_dir = ["public", "functions"]

[triggers]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"

[site]
bucket = "./public"
entry-point = "pages"
