name = "vibration-monitoring-system"
main = "pages/index.js"  # تغییر داده شد
compatibility_date = "2024-01-01"

[env.production]
name = "vibration-monitoring"
compatibility_flags = { nodejs_compat = true }

[env.staging]
name = "vibration-monitoring-staging"
compatibility_flags = { nodejs_compat = true }

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-super-secure-jwt-secret-key-here-change-this"

[[kv_namespaces]]
binding = "DB"
id = "your-database-id-here"  # اضافه شد

[[kv_namespaces]]
binding = "CACHE"
id = "your-cache-id-here"  # اضافه شد

[build]
command = "npm run build"
cwd = "."
watch_dir = ["public", "functions"]

[triggers]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"

[site]
bucket = "./public"
# entry-point حذف شد
